CREATE database information_services;

CREATE TABLE IF NOT EXISTS T_PEOPLE (
	ID SERIAL PRIMARY KEY,
	FULL_NAME VARCHAR(90) NOT NULL,
	PIN VARCHAR(10)
);
INSERT INTO T_PEOPLE(FULL_NAME,PIN) values ('BOGOMIL BORISOV', '0123456789');
INSERT INTO T_PEOPLE(FULL_NAME,PIN) values ('IVAN IVANOV', '542178952');
INSERT INTO T_PEOPLE(FULL_NAME,PIN) values ('KRASIMIR DIMITROV', '0573456789');
INSERT INTO T_PEOPLE(FULL_NAME,PIN) values ('DIMITAR DELCHEV', '0123494789');
INSERT INTO T_PEOPLE(FULL_NAME,PIN) values ('ALEKSANDAR TOTEV', '0123494752');

CREATE TABLE IF NOT EXISTS T_MAILS (
	ID SERIAL PRIMARY KEY,
	T_PEOPLE_ID BIGINT NOT NULL,
	EMAIL_TYPE VARCHAR(5) NOT NULL,
	EMAIL VARCHAR(40)
);
INSERT INTO T_MAILS(T_PEOPLE_ID,EMAIL_TYPE,EMAIL) values (1, 'gmail', 'bogomilborisov99@gmail.com');
INSERT INTO T_MAILS(T_PEOPLE_ID,EMAIL_TYPE,EMAIL) values (2, 'abv', 'ivanivanov@abv.bg');
INSERT INTO T_MAILS(T_PEOPLE_ID,EMAIL_TYPE) values (3, 'yahoo');
INSERT INTO T_MAILS(T_PEOPLE_ID,EMAIL_TYPE) values (4, 'gmail');
INSERT INTO T_MAILS(T_PEOPLE_ID,EMAIL_TYPE,EMAIL) values (5, 'yahoo', 'aleksandartotev@yahoo.com');

CREATE TABLE IF NOT EXISTS T_ADDRESSES (
	ID SERIAL PRIMARY KEY,
	T_PEOPLE_ID BIGINT NOT NULL,
	ADDR_TYPE VARCHAR(5) NOT NULL,
	ADDR_INFO VARCHAR(300)
);
INSERT INTO T_ADDRESSES(T_PEOPLE_ID,ADDR_TYPE,ADDR_INFO) values (1, '', 'ul. Ralevitsa 44A');
INSERT INTO T_ADDRESSES(T_PEOPLE_ID,ADDR_TYPE,ADDR_INFO) values (2, '', 'ul. Ivan Susanin, bl.218');
INSERT INTO T_ADDRESSES(T_PEOPLE_ID,ADDR_TYPE,ADDR_INFO) values (3, '', 'jk.Ovcha Kupel, bl.405, vh.3');
INSERT INTO T_ADDRESSES(T_PEOPLE_ID,ADDR_TYPE) values (4, '');
INSERT INTO T_ADDRESSES(T_PEOPLE_ID,ADDR_TYPE,ADDR_INFO) values (5, '', 'ul. Praga 1, bl.10, vh.A');